### ISSUE TITLE
Nodered overkiz-execute nodes no more working

### ISSUE THREAD

**Issue by tomy-d** [slep88/node-red-contrib-overkiz#10]
Hello slep88,

since a few days all my overkiz-execute nodes do not work anymore.
Using a Tahoma Premium and host: tahomalink.com. It now has worked for years witout any problem.
The node shows a green "execute" but has no effekt - debugging shows no output data
Overkiz-state nodes are working...outputdata is available in debugging
Tahoma Premiun is accessable and funktional with Tahoma App and/or Alexa....
Are there any known issues?!

Thanks in advance!
tomy

**Comment by Wolfvie1** [comment]
I am having exactly the same issue...

**Comment by tomy-d** [comment]
Update: Even though the Overkiz-state request shows an output - this output does not show the current status of my devices.
The status seems to be frozen...
No one with an idea what the problem is? My home automation is really down with that situation!

**Comment by slep88** [comment]
@Wolfvie1 , @tomy-d 
Thanks for notifying. I can reproduce the issue with my setup, too. I‘m already trying to find a solution.

**Comment by tomy-d** [comment]
2nd update:
> called the Somfy support
> asked if there was any lock on my box: Reult:  my box had no lock
> suppord adviced me to reset the hardware
> after the hardware reset my box performend an update
But:
> NO EFFEKT on issue > still no aktion und current status over node-red overkiz-gateway on my devices

**Comment by slep88** [comment]
@Wolfvie1 , @tomy-d
Somfy must have changed something on their servers recently. With the consequence that the known host "tahomalink.com" is behaving kind of strange, which results in the observed issues.

The solution is pretty simple:
Change the host of the gateway node to **"www.tahomalink.com"** and everything is working normal again:
![image](https://github.com/slep88/node-red-contrib-overkiz/assets/52611084/33b0865d-0dba-49e5-b811-4308ae6aa585)

**Comment by tomy-d** [comment]
Good morning slep88

Thanks a lot! 
Changing the configuration to www.tahomalink.com solved the problem!
Thank you also for sharing the overkiz node for noder-red!
Is there any way how I can donate you with paypal?! @slep88 on paypal is it you?!
