### ISSUE TITLE
How set things

### ISSUE THREAD

**Issue by steve41200** [slep88/node-red-contrib-overkiz#2]
Hi
I discovert your node who sound very good for what i search to do.
I can control light who where in jail on a frenchBox (Econnect2) but for control heater i think i'm missing something.
When i try to settemperature or wathelse It return error.
Where can i put value i want to set ? And what is the correct form to do it ?
I have try to put a msg.payload before with value without success

Thanks to show me the correct way to do it

**Comment by slep88** [comment]
Hi Steve,

Your request reminds me that i wanted to do some refactoring and documentation of the nodes. Maybe i will find some time during the upcoming covid lock-down... :)

The execute node expects currently for every command an array of values, even if it has only a single parameter. 

Unfortunately i don‘t have a waterheater to confirm it, but i expect that the payload should look somehow like this:

msg.payload = [ 50.5 ]

Or if it doesn‘t support floating point Numbers:

msg.payload = [ 50 ]

Please let me know if it works and thanks for testing.

Best regards!

**Comment by steve41200** [comment]
Ty for your answer. It works fine with the correct form. I was trying on payload but not like this with [ ]. 
Set temperature don't works, but set comfort temp work. 
I have set heater for prog manually and create a dummie switch who state send to flow with your node. And the switch is the heater of a generic climate in Homeassitant. I can control IO device who were in jail in my Econnectb Box in Homeassistant 👍
