### ISSUE TITLE
This plugin is not working due to login API changes (Cozytouch 3.0)

### ISSUE THREAD

**Issue by jocelyngirard** [slep88/node-red-contrib-overkiz#4]
Hello @slep88,

Since october, the Cozytouch gateway authentication method changed (v3.0)

I do not know the details of this new authentication mode.
I will try to synthesize the changes and make a pull request, I am blocked in my automations.

If you can take a look at how to do this update on your side, that will be great !

**Comment by slep88** [comment]
Hello @jocelyngirard,

with #6 the new version of the [overkiz-api](https://github.com/bbriatte/overkiz-api) has been implemented to the node. The new login method should work now by selecting the "Cozytouch" login handler in the corresponding drop down list of the gateway node.
