### ISSUE TITLE
Which gateway for Hi-Kumo

### ISSUE THREAD

**Issue by SeeDborg** [slep88/node-red-contrib-overkiz#5]
Hello,
I have a Hi-Kumo and I would like to know what to type in the "Host" field when I create a new gateway.

Regards.

**Comment by slep88** [comment]
Hi,

depending on your location, one of the following hosts might work for you:

Europe: ha117-1.overkiz.com
Asia / Oceania: ha203-1.overkiz.com

Found at: https://github.com/iMicknl/python-overkiz-api/blob/main/pyoverkiz/const.py

Best regards

**Comment by SeeDborg** [comment]
It seems to work, thanks !
Now I have to figure out how the node works ^^
